// <auto-generated />
using System;
using AIResumeScreeningSystem.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AIResumeScreeningSystem.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260430170811_AddMatchVerdictAndMissingReqs")]
    partial class AddMatchVerdictAndMissingReqs
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AIResumeScreeningSystem.Models.Applicant", b =>
                {
                    b.Property<int>("ApplicantID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ApplicantID"));

                    b.Property<string>("Achievements")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Address")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("Certifications")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CurrentJobTitle")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("CurrentLocation")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<bool>("DataSharingConsent")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("EmailFrequency")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Gender")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("HighestEducation")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("InAppNotifications")
                        .HasColumnType("bit");

                    b.Property<string>("Languages")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("LastActivityDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("LastLoginDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("LinkedInURL")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("PortfolioURL")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<int>("ProfileCompletionPercent")
                        .HasColumnType("int");

                    b.Property<string>("ProfileSummary")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("ProfileVisibility")
                        .HasColumnType("bit");

                    b.Property<string>("Projects")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ResumeFilePath")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("SearchStatus")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.Property<int>("YearsOfExperience")
                        .HasColumnType("int");

                    b.HasKey("ApplicantID");

                    b.HasIndex("UserID")
                        .IsUnique();

                    b.ToTable("Applicants", (string)null);

                    b.HasData(
                        new
                        {
                            ApplicantID = 1,
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DataSharingConsent = true,
                            EmailFrequency = "Daily",
                            InAppNotifications = true,
                            ProfileCompletionPercent = 0,
                            ProfileVisibility = true,
                            SearchStatus = "active",
                            UserID = 2,
                            YearsOfExperience = 3
                        });
                });

            modelBuilder.Entity("AIResumeScreeningSystem.Models.ApplicantSkill", b =>
                {
                    b.Property<int>("ApplicantSkillID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ApplicantSkillID"));

                    b.Property<int>("ApplicantID")
                        .HasColumnType("int");

                    b.Property<int>("SkillID")
                        .HasColumnType("int");

                    b.Property<string>("SkillLevel")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("ApplicantSkillID");

                    b.HasIndex("ApplicantID");

                    b.HasIndex("SkillID");

                    b.ToTable("ApplicantSkills", (string)null);
                });

            modelBuilder.Entity("AIResumeScreeningSystem.Models.Application", b =>
                {
                    b.Property<int>("ApplicationID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ApplicationID"));

                    b.Property<int?>("ApplicantID")
                        .HasColumnType("int");

                    b.Property<string>("ApplicationStatus")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("ApplicationTrackingID")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("AppliedDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("EducationScore")
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal>("ExperienceScore")
                        .HasColumnType("decimal(5,2)");

                    b.Property<int>("JobID")
                        .HasColumnType("int");

                    b.Property<decimal>("MatchScore")
                        .HasColumnType("decimal(5,2)");

                    b.Property<string>("MatchVerdict")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("MissingRequirements")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ResumeFilePath")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<decimal>("SkillScore")
                        .HasColumnType("decimal(5,2)");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("ApplicationID");

                    b.HasIndex("ApplicantID");

                    b.HasIndex("ApplicationTrackingID")
                        .IsUnique()
                        .HasFilter("[ApplicationTrackingID] IS NOT NULL");

                    b.HasIndex("JobID");

                    b.ToTable("Applications", (string)null);
                });

            modelBuilder.Entity("AIResumeScreeningSystem.Models.Company", b =>
                {
                    b.Property<int>("CompanyID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CompanyID"));

                    b.Property<string>("AboutOrganization")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CompanyLocation")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("CompanyNameBangla")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("CompanySize")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("CompanyStatus")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("CompanyWebsite")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("CoverPhotoPath")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("District")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Division")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("EstablishmentYear")
                        .HasColumnType("int");

                    b.Property<string>("FullAddress")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("FullAddressBangla")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("IndustryType")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("LandPhoneNumber")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("LogoPath")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Mission")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MobileNumber")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("OrganizationCategory")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("OrganizationEmail")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("PostalCode")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("SignaturePath")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Tagline")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Tags")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Thana")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Vision")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CompanyID");

                    b.HasIndex("CompanyName")
                        .IsUnique();

                    b.ToTable("Companies", (string)null);

                    b.HasData(
                        new
                        {
                            CompanyID = 1,
                            CompanyLocation = "Dhaka, Bangladesh",
                            CompanyName = "TechCorp Solutions",
                            CompanySize = "201-500",
                            CompanyStatus = "Active",
                            CompanyWebsite = "https://techcorp.example.com",
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IndustryType = "Information Technology"
                        });
                });

            modelBuilder.Entity("AIResumeScreeningSystem.Models.CreditTransaction", b =>
                {
                    b.Property<int>("TransactionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TransactionID"));

                    b.Property<string>("ActionType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreditsUsed")
                        .HasColumnType("int");

                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.HasKey("TransactionID");

                    b.HasIndex("UserID");

                    b.ToTable("CreditTransactions");
                });

            modelBuilder.Entity("AIResumeScreeningSystem.Models.Interview", b =>
                {
                    b.Property<int>("InterviewID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("InterviewID"));

                    b.Property<int>("ApplicationID")
                        .HasColumnType("int");

                    b.Property<string>("Feedback")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("InterviewDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("InterviewLocation")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("InterviewResult")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<int>("InterviewRound")
                        .HasColumnType("int");

                    b.Property<string>("InterviewStatus")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<TimeSpan>("InterviewTime")
                        .HasColumnType("time");

                    b.Property<string>("InterviewType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("MeetingLink")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("InterviewID");

                    b.HasIndex("ApplicationID");

                    b.ToTable("Interviews", (string)null);
                });

            modelBuilder.Entity("AIResumeScreeningSystem.Models.Job", b =>
                {
                    b.Property<int>("JobID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("JobID"));

                    b.Property<DateTime?>("ApplicationDeadline")
                        .HasColumnType("datetime2");

                    b.Property<string>("AttachmentPath")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int?>("CompanyID")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("EducationLevel")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("JobCategoryID")
                        .HasColumnType("int");

                    b.Property<string>("JobDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("JobLocation")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("JobSector")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("JobStatus")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("JobTitle")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("JobType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("MinimumExperience")
                        .HasColumnType("int");

                    b.Property<int>("RecruiterID")
                        .HasColumnType("int");

                    b.Property<string>("RequiredSkills")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("SalaryMax")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("SalaryMin")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("JobID");

                    b.HasIndex("CompanyID");

                    b.HasIndex("RecruiterID");

                    b.ToTable("Jobs", (string)null);

                    b.HasData(
                        new
                        {
                            JobID = 1,
                            AttachmentPath = "/uploads/jobs/sample_circular.pdf",
                            CompanyID = 1,
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EducationLevel = "BSc",
                            JobDescription = "Exciting opportunity for a Senior .NET Developer at TechCorp.",
                            JobLocation = "Dhaka",
                            JobSector = "Private",
                            JobStatus = "Open",
                            JobTitle = "Senior .NET Developer",
                            JobType = "Contract",
                            MinimumExperience = 3,
                            RecruiterID = 1,
                            RequiredSkills = "C#, ASP.NET Core, SQL Server",
                            SalaryMax = 88000m,
                            SalaryMin = 55000m,
                            UpdatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            JobID = 2,
                            AttachmentPath = "/uploads/jobs/sample_circular.pdf",
                            CompanyID = 1,
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EducationLevel = "BSc",
                            JobDescription = "Exciting opportunity for a Frontend Engineer (React) at TechCorp.",
                            JobLocation = "Chittagong",
                            JobSector = "Private",
                            JobStatus = "Open",
                            JobTitle = "Frontend Engineer (React)",
                            JobType = "Full Time",
                            MinimumExperience = 4,
                            RecruiterID = 2,
                            RequiredSkills = "C#, ASP.NET Core, SQL Server",
                            SalaryMax = 96000m,
                            SalaryMin = 60000m,
                            UpdatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            JobID = 3,
                            AttachmentPath = "/uploads/jobs/sample_circular.pdf",
                            CompanyID = 1,
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EducationLevel = "BSc",
                            JobDescription = "Exciting opportunity for a SQL Database Admin at TechCorp.",
                            JobLocation = "Sylhet",
                            JobSector = "Private",
                            JobStatus = "Open",
                            JobTitle = "SQL Database Admin",
                            JobType = "Contract",
                            MinimumExperience = 5,
                            RecruiterID = 3,
                            RequiredSkills = "C#, ASP.NET Core, SQL Server",
                            SalaryMax = 104000m,
                            SalaryMin = 65000m,
                            UpdatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            JobID = 4,
                            AttachmentPath = "/uploads/jobs/sample_circular.pdf",
                            CompanyID = 1,
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EducationLevel = "BSc",
                            JobDescription = "Exciting opportunity for a DevOps Specialist at TechCorp.",
                            JobLocation = "Remote",
                            JobSector = "Private",
                            JobStatus = "Open",
                            JobTitle = "DevOps Specialist",
                            JobType = "Full Time",
                            MinimumExperience = 6,
                            RecruiterID = 4,
                            RequiredSkills = "C#, ASP.NET Core, SQL Server",
                            SalaryMax = 112000m,
                            SalaryMin = 70000m,
                            UpdatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            JobID = 5,
                            AttachmentPath = "/uploads/jobs/sample_circular.pdf",
                            CompanyID = 1,
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EducationLevel = "BSc",
                            JobDescription = "Exciting opportunity for a Product Manager at TechCorp.",
                            JobLocation = "Dhaka",
                            JobSector = "Private",
                            JobStatus = "Open",
                            JobTitle = "Product Manager",
                            JobType = "Contract",
                            MinimumExperience = 2,
                            RecruiterID = 5,
                            RequiredSkills = "C#, ASP.NET Core, SQL Server",
                            SalaryMax = 120000m,
                            SalaryMin = 75000m,
                            UpdatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            JobID = 6,
                            AttachmentPath = "/uploads/jobs/sample_circular.pdf",
                            CompanyID = 1,
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EducationLevel = "BSc",
                            JobDescription = "Exciting opportunity for a UI/UX Designer at TechCorp.",
                            JobLocation = "Dhaka",
                            JobSector = "Private",
                            JobStatus = "Open",
                            JobTitle = "UI/UX Designer",
                            JobType = "Full Time",
                            MinimumExperience = 3,
                            RecruiterID = 6,
                            RequiredSkills = "C#, ASP.NET Core, SQL Server",
                            SalaryMax = 128000m,
                            SalaryMin = 80000m,
                            UpdatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            JobID = 7,
                            AttachmentPath = "/uploads/jobs/sample_circular.pdf",
                            CompanyID = 1,
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EducationLevel = "BSc",
                            JobDescription = "Exciting opportunity for a QA Automation Engineer at TechCorp.",
                            JobLocation = "Remote",
                            JobSector = "Private",
                            JobStatus = "Open",
                            JobTitle = "QA Automation Engineer",
                            JobType = "Contract",
                            MinimumExperience = 4,
                            RecruiterID = 7,
                            RequiredSkills = "C#, ASP.NET Core, SQL Server",
                            SalaryMax = 136000m,
                            SalaryMin = 85000m,
                            UpdatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            JobID = 8,
                            AttachmentPath = "/uploads/jobs/sample_circular.pdf",
                            CompanyID = 1,
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EducationLevel = "BSc",
                            JobDescription = "Exciting opportunity for a Machine Learning Engineer at TechCorp.",
                            JobLocation = "Dhaka",
                            JobSector = "Private",
                            JobStatus = "Open",
                            JobTitle = "Machine Learning Engineer",
                            JobType = "Full Time",
                            MinimumExperience = 5,
                            RecruiterID = 8,
                            RequiredSkills = "C#, ASP.NET Core, SQL Server",
                            SalaryMax = 144000m,
                            SalaryMin = 90000m,
                            UpdatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            JobID = 9,
                            AttachmentPath = "/uploads/jobs/sample_circular.pdf",
                            CompanyID = 1,
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EducationLevel = "BSc",
                            JobDescription = "Exciting opportunity for a Cloud Architect at TechCorp.",
                            JobLocation = "Chittagong",
                            JobSector = "Private",
                            JobStatus = "Open",
                            JobTitle = "Cloud Architect",
                            JobType = "Contract",
                            MinimumExperience = 6,
                            RecruiterID = 9,
                            RequiredSkills = "C#, ASP.NET Core, SQL Server",
                            SalaryMax = 152000m,
                            SalaryMin = 95000m,
                            UpdatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            JobID = 10,
                            AttachmentPath = "/uploads/jobs/sample_circular.pdf",
                            CompanyID = 1,
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EducationLevel = "BSc",
                            JobDescription = "Exciting opportunity for a Full Stack Developer at TechCorp.",
                            JobLocation = "Remote",
                            JobSector = "Private",
                            JobStatus = "Open",
                            JobTitle = "Full Stack Developer",
                            JobType = "Full Time",
                            MinimumExperience = 2,
                            RecruiterID = 10,
                            RequiredSkills = "C#, ASP.NET Core, SQL Server",
                            SalaryMax = 160000m,
                            SalaryMin = 100000m,
                            UpdatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("AIResumeScreeningSystem.Models.JobSkill", b =>
                {
                    b.Property<int>("JobSkillID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("JobSkillID"));

                    b.Property<string>("ImportanceLevel")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("JobID")
                        .HasColumnType("int");

                    b.Property<int>("SkillID")
                        .HasColumnType("int");

                    b.HasKey("JobSkillID");

                    b.HasIndex("JobID");

                    b.HasIndex("SkillID");

                    b.ToTable("JobSkills", (string)null);
                });

            modelBuilder.Entity("AIResumeScreeningSystem.Models.Recruiter", b =>
                {
                    b.Property<int>("RecruiterID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RecruiterID"));

                    b.Property<int?>("CompanyID")
                        .HasColumnType("int");

                    b.Property<string>("CompanyLocation")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("CompanyName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("CompanySize")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("CompanyWebsite")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Designation")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("IndustryType")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("RecruiterStatus")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.HasKey("RecruiterID");

                    b.HasIndex("CompanyID");

                    b.HasIndex("UserID")
                        .IsUnique();

                    b.ToTable("Recruiters", (string)null);

                    b.HasData(
                        new
                        {
                            RecruiterID = 1,
                            CompanyID = 1,
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Designation = "Technical Recruiter 1",
                            RecruiterStatus = "Active",
                            UserID = 3
                        },
                        new
                        {
                            RecruiterID = 2,
                            CompanyID = 1,
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Designation = "Technical Recruiter 2",
                            RecruiterStatus = "Active",
                            UserID = 4
                        },
                        new
                        {
                            RecruiterID = 3,
                            CompanyID = 1,
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Designation = "Technical Recruiter 3",
                            RecruiterStatus = "Active",
                            UserID = 5
                        },
                        new
                        {
                            RecruiterID = 4,
                            CompanyID = 1,
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Designation = "Technical Recruiter 4",
                            RecruiterStatus = "Active",
                            UserID = 6
                        },
                        new
                        {
                            RecruiterID = 5,
                            CompanyID = 1,
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Designation = "Technical Recruiter 5",
                            RecruiterStatus = "Active",
                            UserID = 7
                        },
                        new
                        {
                            RecruiterID = 6,
                            CompanyID = 1,
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Designation = "Technical Recruiter 6",
                            RecruiterStatus = "Active",
                            UserID = 8
                        },
                        new
                        {
                            RecruiterID = 7,
                            CompanyID = 1,
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Designation = "Technical Recruiter 7",
                            RecruiterStatus = "Active",
                            UserID = 9
                        },
                        new
                        {
                            RecruiterID = 8,
                            CompanyID = 1,
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Designation = "Technical Recruiter 8",
                            RecruiterStatus = "Active",
                            UserID = 10
                        },
                        new
                        {
                            RecruiterID = 9,
                            CompanyID = 1,
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Designation = "Technical Recruiter 9",
                            RecruiterStatus = "Active",
                            UserID = 11
                        },
                        new
                        {
                            RecruiterID = 10,
                            CompanyID = 1,
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Designation = "Technical Recruiter 10",
                            RecruiterStatus = "Active",
                            UserID = 12
                        });
                });

            modelBuilder.Entity("AIResumeScreeningSystem.Models.Skill", b =>
                {
                    b.Property<int>("SkillID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SkillID"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("SkillCategory")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("SkillName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("SkillID");

                    b.ToTable("Skills", (string)null);

                    b.HasData(
                        new
                        {
                            SkillID = 1,
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SkillCategory = "Programming",
                            SkillName = "C#"
                        },
                        new
                        {
                            SkillID = 2,
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SkillCategory = "Framework",
                            SkillName = "ASP.NET Core"
                        },
                        new
                        {
                            SkillID = 3,
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SkillCategory = "Database",
                            SkillName = "SQL Server"
                        });
                });

            modelBuilder.Entity("AIResumeScreeningSystem.Models.User", b =>
                {
                    b.Property<int>("UserID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserID"));

                    b.Property<string>("AccountStatus")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Credits")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<bool>("EmailVerified")
                        .HasColumnType("bit");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<bool>("IsFirstLogin")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastLoginDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("ProfilePicturePath")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("UserID");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users", (string)null);

                    b.HasData(
                        new
                        {
                            UserID = 1,
                            AccountStatus = "Active",
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Credits = 0,
                            Email = "admin@janala.com",
                            EmailVerified = true,
                            FullName = "System Admin",
                            IsFirstLogin = true,
                            PasswordHash = "$2a$11$VEcFQhjlEFKhK/10UGhn3ubUqgorau4zWrIE2nzKTSo3tkBZJXkSm",
                            Role = "Admin",
                            UpdatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            UserID = 2,
                            AccountStatus = "Active",
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Credits = 0,
                            Email = "applicant@janala.com",
                            EmailVerified = true,
                            FullName = "Main Applicant",
                            IsFirstLogin = true,
                            PasswordHash = "$2a$11$VEcFQhjlEFKhK/10UGhn3ubUqgorau4zWrIE2nzKTSo3tkBZJXkSm",
                            Role = "Applicant",
                            UpdatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            UserID = 3,
                            AccountStatus = "Active",
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Credits = 0,
                            Email = "recruiter1@janala.com",
                            EmailVerified = true,
                            FullName = "Recruiter 1",
                            IsFirstLogin = true,
                            PasswordHash = "$2a$11$VEcFQhjlEFKhK/10UGhn3ubUqgorau4zWrIE2nzKTSo3tkBZJXkSm",
                            Role = "Recruiter",
                            UpdatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            UserID = 4,
                            AccountStatus = "Active",
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Credits = 0,
                            Email = "recruiter2@janala.com",
                            EmailVerified = true,
                            FullName = "Recruiter 2",
                            IsFirstLogin = true,
                            PasswordHash = "$2a$11$VEcFQhjlEFKhK/10UGhn3ubUqgorau4zWrIE2nzKTSo3tkBZJXkSm",
                            Role = "Recruiter",
                            UpdatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            UserID = 5,
                            AccountStatus = "Active",
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Credits = 0,
                            Email = "recruiter3@janala.com",
                            EmailVerified = true,
                            FullName = "Recruiter 3",
                            IsFirstLogin = true,
                            PasswordHash = "$2a$11$VEcFQhjlEFKhK/10UGhn3ubUqgorau4zWrIE2nzKTSo3tkBZJXkSm",
                            Role = "Recruiter",
                            UpdatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            UserID = 6,
                            AccountStatus = "Active",
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Credits = 0,
                            Email = "recruiter4@janala.com",
                            EmailVerified = true,
                            FullName = "Recruiter 4",
                            IsFirstLogin = true,
                            PasswordHash = "$2a$11$VEcFQhjlEFKhK/10UGhn3ubUqgorau4zWrIE2nzKTSo3tkBZJXkSm",
                            Role = "Recruiter",
                            UpdatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            UserID = 7,
                            AccountStatus = "Active",
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Credits = 0,
                            Email = "recruiter5@janala.com",
                            EmailVerified = true,
                            FullName = "Recruiter 5",
                            IsFirstLogin = true,
                            PasswordHash = "$2a$11$VEcFQhjlEFKhK/10UGhn3ubUqgorau4zWrIE2nzKTSo3tkBZJXkSm",
                            Role = "Recruiter",
                            UpdatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            UserID = 8,
                            AccountStatus = "Active",
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Credits = 0,
                            Email = "recruiter6@janala.com",
                            EmailVerified = true,
                            FullName = "Recruiter 6",
                            IsFirstLogin = true,
                            PasswordHash = "$2a$11$VEcFQhjlEFKhK/10UGhn3ubUqgorau4zWrIE2nzKTSo3tkBZJXkSm",
                            Role = "Recruiter",
                            UpdatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            UserID = 9,
                            AccountStatus = "Active",
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Credits = 0,
                            Email = "recruiter7@janala.com",
                            EmailVerified = true,
                            FullName = "Recruiter 7",
                            IsFirstLogin = true,
                            PasswordHash = "$2a$11$VEcFQhjlEFKhK/10UGhn3ubUqgorau4zWrIE2nzKTSo3tkBZJXkSm",
                            Role = "Recruiter",
                            UpdatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            UserID = 10,
                            AccountStatus = "Active",
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Credits = 0,
                            Email = "recruiter8@janala.com",
                            EmailVerified = true,
                            FullName = "Recruiter 8",
                            IsFirstLogin = true,
                            PasswordHash = "$2a$11$VEcFQhjlEFKhK/10UGhn3ubUqgorau4zWrIE2nzKTSo3tkBZJXkSm",
                            Role = "Recruiter",
                            UpdatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            UserID = 11,
                            AccountStatus = "Active",
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Credits = 0,
                            Email = "recruiter9@janala.com",
                            EmailVerified = true,
                            FullName = "Recruiter 9",
                            IsFirstLogin = true,
                            PasswordHash = "$2a$11$VEcFQhjlEFKhK/10UGhn3ubUqgorau4zWrIE2nzKTSo3tkBZJXkSm",
                            Role = "Recruiter",
                            UpdatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            UserID = 12,
                            AccountStatus = "Active",
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Credits = 0,
                            Email = "recruiter10@janala.com",
                            EmailVerified = true,
                            FullName = "Recruiter 10",
                            IsFirstLogin = true,
                            PasswordHash = "$2a$11$VEcFQhjlEFKhK/10UGhn3ubUqgorau4zWrIE2nzKTSo3tkBZJXkSm",
                            Role = "Recruiter",
                            UpdatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("AIResumeScreeningSystem.Models.Applicant", b =>
                {
                    b.HasOne("AIResumeScreeningSystem.Models.User", "User")
                        .WithOne("Applicant")
                        .HasForeignKey("AIResumeScreeningSystem.Models.Applicant", "UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("AIResumeScreeningSystem.Models.ApplicantSkill", b =>
                {
                    b.HasOne("AIResumeScreeningSystem.Models.Applicant", "Applicant")
                        .WithMany("ApplicantSkills")
                        .HasForeignKey("ApplicantID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AIResumeScreeningSystem.Models.Skill", "Skill")
                        .WithMany("ApplicantSkills")
                        .HasForeignKey("SkillID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Applicant");

                    b.Navigation("Skill");
                });

            modelBuilder.Entity("AIResumeScreeningSystem.Models.Application", b =>
                {
                    b.HasOne("AIResumeScreeningSystem.Models.Applicant", "Applicant")
                        .WithMany("Applications")
                        .HasForeignKey("ApplicantID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("AIResumeScreeningSystem.Models.Job", "Job")
                        .WithMany("Applications")
                        .HasForeignKey("JobID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Applicant");

                    b.Navigation("Job");
                });

            modelBuilder.Entity("AIResumeScreeningSystem.Models.CreditTransaction", b =>
                {
                    b.HasOne("AIResumeScreeningSystem.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("AIResumeScreeningSystem.Models.Interview", b =>
                {
                    b.HasOne("AIResumeScreeningSystem.Models.Application", "Application")
                        .WithMany("Interviews")
                        .HasForeignKey("ApplicationID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Application");
                });

            modelBuilder.Entity("AIResumeScreeningSystem.Models.Job", b =>
                {
                    b.HasOne("AIResumeScreeningSystem.Models.Company", "Company")
                        .WithMany("Jobs")
                        .HasForeignKey("CompanyID")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("AIResumeScreeningSystem.Models.Recruiter", "Recruiter")
                        .WithMany("Jobs")
                        .HasForeignKey("RecruiterID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Company");

                    b.Navigation("Recruiter");
                });

            modelBuilder.Entity("AIResumeScreeningSystem.Models.JobSkill", b =>
                {
                    b.HasOne("AIResumeScreeningSystem.Models.Job", "Job")
                        .WithMany("JobSkills")
                        .HasForeignKey("JobID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AIResumeScreeningSystem.Models.Skill", "Skill")
                        .WithMany("JobSkills")
                        .HasForeignKey("SkillID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Job");

                    b.Navigation("Skill");
                });

            modelBuilder.Entity("AIResumeScreeningSystem.Models.Recruiter", b =>
                {
                    b.HasOne("AIResumeScreeningSystem.Models.Company", "Company")
                        .WithMany("Recruiters")
                        .HasForeignKey("CompanyID")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("AIResumeScreeningSystem.Models.User", "User")
                        .WithOne("Recruiter")
                        .HasForeignKey("AIResumeScreeningSystem.Models.Recruiter", "UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");

                    b.Navigation("User");
                });

            modelBuilder.Entity("AIResumeScreeningSystem.Models.Applicant", b =>
                {
                    b.Navigation("ApplicantSkills");

                    b.Navigation("Applications");
                });

            modelBuilder.Entity("AIResumeScreeningSystem.Models.Application", b =>
                {
                    b.Navigation("Interviews");
                });

            modelBuilder.Entity("AIResumeScreeningSystem.Models.Company", b =>
                {
                    b.Navigation("Jobs");

                    b.Navigation("Recruiters");
                });

            modelBuilder.Entity("AIResumeScreeningSystem.Models.Job", b =>
                {
                    b.Navigation("Applications");

                    b.Navigation("JobSkills");
                });

            modelBuilder.Entity("AIResumeScreeningSystem.Models.Recruiter", b =>
                {
                    b.Navigation("Jobs");
                });

            modelBuilder.Entity("AIResumeScreeningSystem.Models.Skill", b =>
                {
                    b.Navigation("ApplicantSkills");

                    b.Navigation("JobSkills");
                });

            modelBuilder.Entity("AIResumeScreeningSystem.Models.User", b =>
                {
                    b.Navigation("Applicant");

                    b.Navigation("Recruiter");
                });
#pragma warning restore 612, 618
        }
    }
}
